/**
 * Dictionary Seed SQL Generator
 *
 * Reads EXPANDED_WORDS_SEED and writes supabase/sql/phase-6h-core-dictionary-seed.sql.
 * Run: npx tsx scripts/generate-dictionary-seed-sql.ts
 *
 * The generated SQL is idempotent (DELETE cascade + INSERT ON CONFLICT DO NOTHING).
 * Run it manually in Supabase SQL Editor after phase-6a schema is applied.
 */

import { writeFileSync } from 'fs'
import { join } from 'path'
import { EXPANDED_WORDS_SEED } from '../data/dictionary/import/core-words-expanded'
import { toDbSourceType } from '../lib/dictionary/dictionary-import-types'

function esc(s: string | null | undefined): string {
  if (s == null) return 'NULL'
  return `'${s.replace(/'/g, "''")}'`
}

function cefrToLevel(cefr?: string): string {
  switch (cefr) {
    case 'A1': return 'beginner'
    case 'A2': return 'elementary'
    case 'B1': return 'intermediate'
    case 'B2': return 'advanced'
    case 'C1': case 'C2': return 'exam-prep'
    default: return 'intermediate'
  }
}

const lines: string[] = []

lines.push(`-- ============================================================`)
lines.push(`-- LexiOcean Phase 6H: Expanded Dictionary Seed (74 words)`)
lines.push(`-- ============================================================`)
lines.push(`-- Generated by scripts/generate-dictionary-seed-sql.ts`)
lines.push(`-- Run AFTER phase-6a-dictionary-pronunciation-schema.sql`)
lines.push(`-- Run in Supabase SQL Editor. Safe to re-run (DELETE cascade + INSERT).`)
lines.push(`--`)
lines.push(`-- COMPLIANCE: All content is original LexiOcean educational material.`)
lines.push(`-- source_type = 'original' for all rows.`)
lines.push(`-- ============================================================`)
lines.push(``)

// Step 1: Delete existing entries (cascade cleans related tables)
const idList = EXPANDED_WORDS_SEED.map(e => esc(e.normalizedWord)).join(',\n  ')
lines.push(`-- Step 1: Delete existing phase-6h entries (cascade cleans related tables)`)
lines.push(`DELETE FROM dictionary_words WHERE id IN (`)
lines.push(`  ${idList}`)
lines.push(`);`)
lines.push(``)

// Step 2: dictionary_words
lines.push(`-- Step 2: dictionary_words`)
lines.push(`INSERT INTO dictionary_words`)
lines.push(`  (id, word, normalized_word, phonetic_ipa, part_of_speech, cefr_level, level,`)
lines.push(`   difficulty, is_core_word, is_exam_word, source_type, source_note, created_at, updated_at)`)
lines.push(`VALUES`)
const wordRows = EXPANDED_WORDS_SEED.map(e => {
  const srcType = toDbSourceType(e.sourceType)
  const level = cefrToLevel(e.cefrLevel)
  return `  (${esc(e.normalizedWord)},${esc(e.word)},${esc(e.normalizedWord)},${esc(e.ipa ?? null)},${esc(e.partOfSpeech[0])},${esc(e.cefrLevel ?? null)},${esc(level)},${e.difficultyLevel ?? 3},${e.isCoreWord ? 'true' : 'false'},${e.isExamWord ? 'true' : 'false'},${esc(srcType)},${esc(e.sourceNote)},NOW(),NOW())`
})
lines.push(wordRows.join(',\n') + ';')
lines.push(``)

// Step 3: dictionary_definitions
const defRows: string[] = []
for (const e of EXPANDED_WORDS_SEED) {
  const enDefs = e.definitions.filter(d => d.language === 'en')
  const zhDefs = e.definitions.filter(d => d.language === 'zh')
  for (let i = 0; i < enDefs.length; i++) {
    const srcType = toDbSourceType(e.sourceType)
    defRows.push(`  (${esc(e.normalizedWord)},${esc(e.partOfSpeech[0])},${esc(enDefs[i].definition)},${esc(zhDefs[i]?.definition ?? null)},${i},${esc(srcType)})`)
  }
}
lines.push(`-- Step 3: dictionary_definitions`)
if (defRows.length > 0) {
  lines.push(`INSERT INTO dictionary_definitions (word_id, part_of_speech, definition_en, definition_zh, order_index, source_type) VALUES`)
  lines.push(defRows.join(',\n') + ';')
} else {
  lines.push(`-- No definitions to insert`)
}
lines.push(``)

// Step 4: dictionary_examples
const exRows: string[] = []
for (const e of EXPANDED_WORDS_SEED) {
  for (let i = 0; i < (e.examples ?? []).length; i++) {
    const ex = e.examples![i]
    const srcType = toDbSourceType(e.sourceType)
    exRows.push(`  (${esc(e.normalizedWord)},${esc(ex.sentenceEn)},${esc(ex.sentenceZh ?? null)},${i},${esc(srcType)})`)
  }
}
lines.push(`-- Step 4: dictionary_examples`)
if (exRows.length > 0) {
  lines.push(`INSERT INTO dictionary_examples (word_id, sentence_en, sentence_zh, order_index, source_type) VALUES`)
  lines.push(exRows.join(',\n') + ';')
} else {
  lines.push(`-- No examples to insert`)
}
lines.push(``)

// Step 5: dictionary_synonyms
const synRows: string[] = []
for (const e of EXPANDED_WORDS_SEED) {
  for (let i = 0; i < (e.synonyms ?? []).length; i++) {
    synRows.push(`  (${esc(e.normalizedWord)},${esc(e.synonyms![i])},${i})`)
  }
}
lines.push(`-- Step 5: dictionary_synonyms`)
if (synRows.length > 0) {
  lines.push(`INSERT INTO dictionary_synonyms (word_id, synonym, order_index) VALUES`)
  lines.push(synRows.join(',\n') + ';')
} else {
  lines.push(`-- No synonyms to insert`)
}
lines.push(``)

// Step 6: dictionary_antonyms
const antRows: string[] = []
for (const e of EXPANDED_WORDS_SEED) {
  for (let i = 0; i < (e.antonyms ?? []).length; i++) {
    antRows.push(`  (${esc(e.normalizedWord)},${esc(e.antonyms![i])},${i})`)
  }
}
lines.push(`-- Step 6: dictionary_antonyms`)
if (antRows.length > 0) {
  lines.push(`INSERT INTO dictionary_antonyms (word_id, antonym, order_index) VALUES`)
  lines.push(antRows.join(',\n') + ';')
} else {
  lines.push(`-- No antonyms to insert`)
}
lines.push(``)

// Step 7: exam_word_tags
const tagRows: string[] = []
for (const e of EXPANDED_WORDS_SEED) {
  for (const tag of e.examTags ?? []) {
    tagRows.push(`  (${esc(e.normalizedWord)},${esc(tag)})`)
  }
}
lines.push(`-- Step 7: exam_word_tags`)
if (tagRows.length > 0) {
  lines.push(`INSERT INTO exam_word_tags (word_id, exam_type) VALUES`)
  lines.push(tagRows.join(',\n'))
  lines.push(`ON CONFLICT (word_id, exam_type) DO NOTHING;`)
} else {
  lines.push(`-- No exam tags to insert`)
}
lines.push(``)
lines.push(`-- End of Phase 6H seed`)

const outPath = join(__dirname, '..', 'supabase', 'sql', 'phase-6h-core-dictionary-seed.sql')
writeFileSync(outPath, lines.join('\n'), 'utf-8')
console.log(`✓ Written: ${outPath}`)
console.log(`  Words:       ${EXPANDED_WORDS_SEED.length}`)
console.log(`  Definitions: ${defRows.length}`)
console.log(`  Examples:    ${exRows.length}`)
console.log(`  Synonyms:    ${synRows.length}`)
console.log(`  Antonyms:    ${antRows.length}`)
console.log(`  Exam tags:   ${tagRows.length}`)
console.log(`\nNext: run this SQL manually in Supabase SQL Editor.`)
